#!/bin/bash
# This program is to test whether it's a file or a directory
# Exit the program if the file/dir is not available.
# Output the file types
# output the attribute of this file/dir for thie executor

# Version 0.1
# Author: wang long
# Date: 2013-06
read -p "please input the file or directory name:" filename
[ -z $filename ] && echo "You MUST input a file name." && exit 0

[ ! -e $filename ] && echo "file is not availabe." && exit 0

[ -f $filename ] && filetype="regular file."
[ -d $filename ] && filetype="dirctory"

[ -r $filename ] && perm="readable"
[ -w $filename ] && perm="$perm, writable"
[ -x $filename ] && perm="$perm, executable"

echo "The filename: '$filename' is a $filetype"
echo "and the permission are: $perm"
